# Golang file

# NOTE: Colors are in RGB format.

[keywords]
patterns = ["func", "var", "const", "type", "struct", "if", "else", "for", "range", "return", "import", "package", "case"]
color = "161, 107, 255" # Purple

[types]
patterns = ["int", "float64", "string", "bool", "map", "slice"]
color = "161, 107, 255" # Purple

[comments]
patterns = ["//.*", "/\\*[^*]*\\*+(?:[^/*][^*]*\\*+)*/"]
color = "99, 96, 93" # Gray

[strings]
patterns = ["\"(?:\\\\.|[^\\\\\"])*\"", "'(?:\\\\.|[^\\\\'])*'"]
color = "217, 162, 113" # Orange

[numbers]
patterns = ["\\b\\d+(?:\\.\\d+)?\\b"]
color = "217, 162, 113" # Orange

[operators]
patterns = ["\\+\\+", "--", "\\+=", "-=", "\\*=", "/=", "&&", "\\|\\|", "!=", "==", "<=", ">=", "\\+", "-", "\\*", "/", "%", "!", "=", ":=", "<", ">", "\\{", "\\}", "\\[", "\\]", "\\(", "\\)"]
color = "161, 107, 255" # Purple

[methods]
patterns = ["\\b\\w+\\s*\\("]
color = "84, 132, 227" # Blue